# ASK mostafa about the kubernetes permissions per each IAM rule

apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
data:
  # mapAccounts: |
  #   - "{{ .Values.accountId }}"
  mapRoles: |
    {{- range .Values.nodegroup_role }}
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::{{ $.Values.accountId }}:role/{{ . }}"
      "username": "system:node:{{`{{`}}EC2PrivateDNSName{{`}}`}}"
    {{- end }}
    {{- range .Values.iam_admin_roles }}
    - "groups":
      - "owners:admin"
      "rolearn": "arn:aws:iam::{{ $.Values.accountId }}:role/{{ . }}"
      "username": {{ . | quote }}
    {{- end }}
